<?php

function _campaignion_google_analytics_load_payment($nid, $sid) {
  $subquery = db_select('campaignion_activity_webform', 'w')
    ->fields('w', array('activity_id'))
    ->condition('nid', $nid)
    ->condition('sid', $sid);
  $pid = db_select('campaignion_activity_payment', 'p')
    ->fields('p', array('pid'))
    ->condition('p.activity_id', $subquery, 'in')
    ->execute()
    ->fetchColumn();
  if ($pid) {
    $payments = entity_load('payment', array($pid));
    return array_shift($payments);
  } else {
    return false;
  }
}

/**
 * Implements hook_init().
 */

function campaignion_google_analytics_node_view($node, $view_mode, $langcode) {
  if ($node->type == 'donation' || $node->type == 'donation2' || $node->type == 'sponsorship') {
    drupal_add_js(drupal_get_path('module', 'campaignion_google_analytics') . '/donation.js');
    if ($view_mode == 'full') {
      drupal_add_js(
        array(
          'campaignion_google_analytics' => array(
            'view' => array(
              'nid' => $node->nid,
              'title' => $node->title,
              'lang' => $node->language,
            ),
          ),
        ),
        'setting');
    } else if ($view_mode == 'teaser') {
      drupal_add_js(
        array(
          'campaignion_google_analytics' => array(
            'impressions' => array(
              $node->nid => array(
                'nid' => $node->nid,
                'title' => $node->title,
                'lang' => $node->language,
              ),
            ),
          ),
        ),
        'setting');
    }
  }
}

function campaignion_google_analytics_page_build(&$page) {
  $parameters = drupal_get_query_parameters();
  if (!isset($parameters['share']) || !isset($parameters['sid'])) {
    return;
  }

  // as long as share and sid are there, we are on a thank you page.
  drupal_add_js(array('campaignion_google_analytics' => array(
        'thank_you' => True
      )), 'setting');

  $nid = intval(explode('/', $parameters['share'])[1]);
  $sid = intval($parameters['sid']);
  $submission = \Drupal\little_helpers\Webform\Submission::load($nid, $sid);
  $node = $submission->getNode();

  if ($payment = _campaignion_google_analytics_load_payment($nid, $sid)) {
    $donation_title = $node->title;
    $donation_lang = $node->language;
    $interval = '';
    switch ($submission->valueByKey('donation_interval')) {
    case '1':
      $interval = 'only once';
      break;
    case 'm':
      $interval = 'monthly';
      break;
    case 'y':
      $interval = 'yearly';
      break;
    }
    $ga_product_name = $donation_title . ' [' . $donation_lang . '] [' . $interval . ']';
    drupal_add_js(
      array(
        'campaignion_google_analytics' => array(
          'nid' => $node->nid,
          'title' => $node->title,
          'lang' => $node->language,
          'payment' => array(
            'id' => $payment->pid,
            'name' => $ga_product_name,
            'price' => $payment->totalAmount(false),
            'category' => $interval,
            'currency' => $payment->currency_code,
            'quantity' => '1',
          ))),
      'setting');
  }
  drupal_add_js(drupal_get_path('module', 'campaignion_google_analytics') . '/thank_you_page.js');
}
