<?php

function _campaignion_google_analytics_load_payment($nid, $sid) {
  $subquery = db_select('campaignion_activity_webform', 'w')
    ->fields('w', array('activity_id'))
    ->condition('nid', $nid)
    ->condition('sid', $sid);
  $pid = db_select('campaignion_activity_payment', 'p')
    ->fields('p', array('pid'))
    ->condition('p.activity_id', $subquery, 'in')
    ->execute()
    ->fetchColumn();
  if ($pid) {
    $payments = entity_load('payment', array($pid));
    return array_shift($payments);
  } else {
    return false;
  }
}

/**
 * Implements hook_init().
 */

function campaignion_google_analytics_page_build(&$page) {
  $parameters = drupal_get_query_parameters();
  if (!isset($parameters['share']) || !isset($parameters['sid'])) {
    return;
  }

  // as long as share and sid are there, we are on a thank you page.
  drupal_add_js(array('campaignion_google_analytics' => array(
        'thank_you' => True
      )), 'setting');

  $nid = intval(explode('/', $parameters['share'])[1]);
  $sid = intval($parameters['sid']);
  $submission = \Drupal\little_helpers\Webform\Submission::load($nid, $sid);

  if ($payment = _campaignion_google_analytics_load_payment($nid, $sid)) {
    drupal_add_js(
      array(
        'campaignion_google_analytics' => array(
          'payment' => array(
            'id' => $payment->pid,
            'name' => drupal_get_title() . ' (' . variable_get('site_name') . ')',
            'price' => $payment->totalAmount(false),
            'category' => $submission->valueByKey('donation_interval'),
            'currency' => $payment->currency_code,
            'quantity' => '1',
          ))),
      'setting');
  }
  drupal_add_js(drupal_get_path('module', 'campaignion_google_analytics') . '/thank_you_page.js');
}