<?php

/**
 * Implements hook_node_insert()
 */
function action_node_insert($node) {
  if (isset($node->action) || Drupal\campaignion\ActionType::isAction($node->type)) {
    $action = Drupal\campaignion\Action::fromNode($node);
    $action->applyDefaultTemplate();
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 * Implements hook_form_webform_client_form_alter().
 *
 * Insert a custom submit handler.
 */
function action_form_webform_client_form_alter(&$form, &$form_state) {
  $form['#submit'][] = '_action_webform_share_redirect';
}

/**
 * Form-submit callback for webform_client_form.
 *
 * Make all share_light-forms on the Thank-You-Page share the
 * action by adding $_GET['share'] to the redirect URL.
 */
function _action_webform_share_redirect($form, &$form_state) {
  if (!$form_state['webform_completed'] || !$form_state['redirect'])
    return;

  $action_path = 'node/' . $form['#node']->nid;
  if (is_array($form_state['redirect'])) {
    $form_state['redirect'][1]['query']['share'] = $action_path;
  } else {
    $form_state['redirect'] = array(
      $form_state['redirect'],
      array('query' => array('share' => $action_path)),
    );
  }
}
