<?php

/**
 * Implements hook_language_switch_links_alter().
 *
 * Remove switch links to non-node_view() paths created by the translation module.
 * This is to avoid geoip_language_redirect from redirecting there.
 */
function campaignion_language_switch_links_alter(array &$links, $type, $path) {
  $language_type = variable_get('translation_language_type', LANGUAGE_TYPE_INTERFACE);

  if ($type == $language_type && preg_match("!^node/(\d+)(/.+|)!", $path, $matches)) {
    if (!empty($matches[2]) && $matches[2] != '/' && $matches[2] != '/view') {
      $node = node_load((int) $matches[1]);
      foreach ($links as $langcode => &$link) {
        if ($langcode != $node->language && isset($link['href'])) {
          // No translation in this language, or no permission to view.
          unset($link['href']);
          $link['attributes']['class'][] = 'locale-untranslated';
        }
      }
    }
  }
}
