<?php
/**
 * @file
 * Code for the campaignion_mp_fields feature.
 */

use \Drupal\campaignion_mp_fields\MPDataLoader;

include_once 'campaignion_mp_fields.features.inc';

/**
 * Implements hook_entity_presave().
 */
function campaignion_mp_fields_entity_presave($entity, $entity_type) {
  MPDataLoader::fromConfig()->setData($entity_type, $entity);
}

/**
 * Implements hook_campaignion_manage_filter_info().
 */
function campaignion_mp_fields_campaignion_manage_filter_info() {
  $filter['supporter']['mp_constituency'] = \Drupal\campaignion_mp_fields\ConstituencyFilter::class;
  $filter['supporter']['mp_country'] = \Drupal\campaignion_mp_fields\CountryFilter::class;
  $filter['supporter']['mp_party'] = \Drupal\campaignion_mp_fields\PartyFilter::class;
  $filter['supporter']['mp_salutation'] = \Drupal\campaignion_mp_fields\SalutationFilter::class;
  return $filter;
}
