<?php
/**
 * @file
 * Code for the Campaignion source tags feature.
 */

use Drupal\campaignion_supporter_tags\Tagger;

include_once 'campaignion_source_tags.features.inc';

/**
 * Implements hook_campaignion_action_contact_alter().
 */
function campaignion_source_tags_campaignion_action_contact_alter($contact, $submission, $action_node) {
  if (!isset($contact->supporter_tags)) {
    return FALSE;
  }

  $changed = FALSE;
  if (!empty($submission->tracking->source)) {
    $tag = $submission->tracking->source;
    $tagger = Tagger::byNameAndParentUuid('supporter_tags', '0fd2977e-9927-4de7-b4c2-e0bde71fc605');
    $changed = $tagger->tag($contact->supporter_tags, [$tag], TRUE) || $changed;
  }

  return $changed;
}

/**
 * Implements hook_entity_presave().
 */
function campaignion_source_tags_entity_presave($entity, $entity_type) {
  if (isset($entity->supporter_tags) && isset($entity->source_tag)) {
    $wrapped = entity_metadata_wrapper($entity_type, $entity);
    if (!$wrapped->source_tag->value()) {
      foreach ($wrapped->supporter_tags->value() as $term) {
        // Check whether the term is a source tag.
        foreach (taxonomy_get_parents($term->tid) as $pterm) {
          if ($pterm->uuid == '0fd2977e-9927-4de7-b4c2-e0bde71fc605') {
            $wrapped->source_tag->set($term);
            break 2;
          }
        }
      }
    }
  }
}
