<?php

/**
 * @file
 * Code for the Campaignion source tags feature.
 */

use Drupal\campaignion_supporter_tags\Tagger;

include_once 'campaignion_source_tags.features.inc';

/**
 * Implements hook_campaignion_action_contact_alter().
 */
function campaignion_source_tags_campaignion_action_contact_alter($contact, $submission, $action_node) {
  if (!isset($contact->supporter_tags)) {
    return FALSE;
  }
  $add_tags = variable_get_value('campaignion_source_tags_new_tags');

  $changed = FALSE;
  if (!empty($submission->tracking->source)) {
    $tag = $submission->tracking->source;
    $tagger = Tagger::byNameAndParentUuid('supporter_tags', '0fd2977e-9927-4de7-b4c2-e0bde71fc605');
    $changed = $tagger->tag($contact->supporter_tags, [$tag], $add_tags) || $changed;
  }

  return $changed;
}

/**
 * Implements hook_entity_presave().
 */
function campaignion_source_tags_entity_presave($entity, $entity_type) {
  $wrapped = entity_metadata_wrapper($entity_type, $entity);
  if (isset($wrapped->supporter_tags) && isset($wrapped->source_tag)) {
    if (!$wrapped->source_tag->value()) {
      foreach ($wrapped->supporter_tags->value() as $term) {
        // Check whether the term is a source tag.
        foreach (taxonomy_get_parents($term->tid) as $pterm) {
          if ($pterm->uuid == '0fd2977e-9927-4de7-b4c2-e0bde71fc605') {
            $wrapped->source_tag->set($term);
            break 2;
          }
        }
      }
    }
  }
}

/**
 * Implements hook_redhen_settings().
 */
function campaignion_action_redhen_settings() {
  $form['tags'] = [
    '#type' => 'fieldset',
    '#title' => t('Tags'),
  ];
  $form['tags']['campaignion_source_tags_new_tags'] = [
    '#type' => 'checkbox',
    '#title' => t('Allow new tags to be added using source URL parameters.'),
    '#default_value' => variable_get_value('campaignion_source_tags_new_tags'),
  ];
  return $form;
}
