<?php

/**
 * Implements hook_node_presave().
 */
function campaignion_action_node_presave($node) {
  if (isset($node->action) || Drupal\campaignion\Action\TypeBase::isAction($node->type)) {
    $action = Drupal\campaignion\Action::fromNode($node);
    $action->presave();
  }
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 * Implements hook_form_webform_client_form_alter().
 *
 * Insert a custom submit handler.
 */
function campaignion_action_form_webform_client_form_alter(&$form, &$form_state) {
  $form['#submit'][] = '_campaignion_action_webform_share_redirect';
}

/**
 * Form-submit callback for webform_client_form.
 *
 * Make all share_light-forms on the Thank-You-Page share the
 * action by adding $_GET['share'] to the redirect URL.
 */
function _campaignion_action_webform_share_redirect($form, &$form_state) {
  if (!$form_state['webform_completed'] || !$form_state['redirect'])
    return;

  $action_path = 'node/' . $form['#node']->nid;
  if (is_array($form_state['redirect'])) {
    $form_state['redirect'][1]['query']['share'] = $action_path;
  } else {
    $form_state['redirect'] = array(
      $form_state['redirect'],
      array('query' => array('share' => $action_path)),
    );
  }
}
