<?php
/**
 * @file
 * Campaignion newsletter Mailchimp integration module.
 */

use \Drupal\campaignion_newsletters_mailchimp\MailChimp;

/**
* Implements hook_libraries_info().
*
* for mailchimps php api library.
*/
function campaignion_newsletters_mailchimp_libraries_info() {
  $libraries['mailchimp-api-php'] = array(
    'name' => 'Mailchimp',
    'vendor url' => 'http://mailchimp.com',
    'download url' => 'https://bitbucket.org/mailchimp/mailchimp-api-php',
    'version' => '2.0.4',
    'files' => array(
      'php' => array('src/Mailchimp.php')
    ),
  );
  return $libraries;
}


/**
 * Implements hook_campaignion_newsletters_provider_info().
 */
function campaignion_newsletters_mailchimp_campaignion_newsletters_provider_info() {
  $keys = variable_get('mailchimp_api_keys', array());
  $providers = array();
  foreach ($keys as $name => $key) {
    $providers['MailChimp-' . $name] = array(
      'class' => '\\Drupal\\campaignion_newsletters_mailchimp\\MailChimp',
      'params' => array('name' => $name, 'key' => $key),
    );
  }
  return $providers;
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Implements hook_form_campaignion_newsletters_admin_settings_alter().
 */
function campaignion_newsletters_mailchimp_form_campaignion_newsletters_admin_settings_alter(&$form, &$form_state) {
  form_load_include($form_state, 'php', 'campaignion_newsletters_mailchimp', 'includes/admin_pages');
  _campaignion_newsletters_mailchimp_form_campaignion_newsletters_admin_settings_alter($form, $form_state);
}

/**
 * Get API-key by machine name.
 */
function campaignion_newsletters_mailchimp_get_key($name) {
  $keys = variable_get('mailchimp_api_keys', array());
  if (isset($keys[$name])) {
    return $keys[$name];
  }
}
