<?php

/**
 * @file
 * Hook implementations & callbacks for the campaignion_donation_amount module.
 */

use Drupal\campaignion_donation_amount\Utils;

/**
 * Implements hook_webform_component_render_alter().
 */
function campaignion_donation_amount_webform_component_render_alter(array &$element, array &$component) {
  if (Utils::isAmountComponent($component)) {
    $info = element_info($element['#type']);
    $element += [
      '#element_validate' => $info['#element_validate'] ?? [],
    ];
    $element['#element_validate'][] = 'campaignion_donation_amount_validate';
    // Always show the select_or_other textfield.
    $element['#attributes']['data-select-or-other-hide'] = 0;
  }
}

/**
 * Element validator for donation_amount.
 */
function campaignion_donation_amount_validate($element, &$form_state, $form) {
  $value = &drupal_array_get_nested_value($form_state['values'], $element['#parents']);

  if ($value === NULL) {
    return;
  }

  $num = (int) $value;
  if ((string) $num != $value || $num < 1) {
    form_error($element, t('Please enter a whole-numbered amount of at least 1.'));
  }
}

/**
 * Implements hook_element_info_alter().
 */
function campaignion_donation_amount_element_info_alter(&$type) {
  $type['select_or_other']['#process'][] = '_campaignion_donation_amount_select_or_other_process';
}

/**
 * Change how select_or_other is displayed for donation_amount components.
 */
function _campaignion_donation_amount_select_or_other_process($element, &$form_state) {
  if (!($component = $element['#webform_component'] ?? NULL)) {
    return $element;
  }
  if (Utils::isAmountComponent($component)) {
    if ($symbol = variable_get_value('campaignion_donation_amount_currency_symbol')) {
      // Use the currency symbol as label.
      $element['other']['#title'] = $symbol;
      unset($element['other']['#title_display']);
    }
  }
  return $element;
}
