<?php

/**
 * @file
 * Hook implementations & callbacks for the campaignion_donation_amount module.
 */


/**
 * Check whether a webform component is a donation amount component.
 */
function _campaignion_donation_amount_component_is_amount($component) {
  return $component['form_key'] == 'donation_amount' || in_array('donation-amount', explode(' ', $component['extra']['wrapper_classes'] ?? ''));
}

/**
 * Implements hook_webform_component_render_alter().
 */
function campaignion_donation_amount_webform_component_render_alter(array &$element, array &$component) {
  if (_campaignion_donation_amount_component_is_amount($component)) {
    $info = element_info($element['#type']);
    $element += [
      '#element_validate' => $info['#element_validate'] ?? [],
    ];
    $element['#element_validate'][] = 'campaignion_donation_amount_validate';
    $element['#attributes']['data-select-or-other-hide'] = 0;
  }
}

/**
 * Element validator for donation_amount.
 */
function campaignion_donation_amount_validate($element, &$form_state, $form) {
  $value = &drupal_array_get_nested_value($form_state['values'], $element['#parents']);

  if ($value === NULL) {
    return;
  }

  $num = (int) $value;
  if ((string) $num != $value || $num < 1) {
    form_error($element, t('Please enter a whole-numbered amount of at least 1.'));
  }
}

/**
 * Implements hook_element_info_alter().
 */
function campaignion_donation_amount_element_info_alter(&$type) {
  $type['select_or_other']['#process'][] = '_campaignion_donation_amount_select_or_other_process';
}

/**
 * Change how select_or_other is displayed for donation_amount components.
 */
function _campaignion_donation_amount_select_or_other_process($element, &$form_state) {
  if (!($component = $element['#webform_component'] ?? NULL)) {
    return $element;
  }
  if (_campaignion_donation_amount_component_is_amount($component)) {
    // add a currency symbol as label
    $element['other']['#title'] = variable_get_value('campaignion_donation_amount_currency_symbol');
    unset($element['other']['#title_display']);
    if ($element['#select_type'] ?? '' == 'radios') {
      // always show other textfield (needs opt-out patch for select_or_other)
      $element['#attributes']['class'][] = 'select-or-other-disabled-js';
    }
  }
  return $element;
}
