<?php

/**
 * @file
 * Hook implementations callbacks for this module.
 */

use \Drupal\manual_direct_debit_uk\AccountDataController;

/**
 * Implements hook_payment_forms_payment_form_alter().
 */
function campaignion_loqate_payment_forms_payment_form_alter(&$form, \Payment $payment) {
  if (!($payment->method->controller instanceof AccountDataController)) {
    return;
  }
  if (!($key = variable_get_value('campaignion_loqate_api_key'))) {
    return;
  }
  $form['#attributes']['class'][] = 'loqate-validate';
  $settings['sortCodeEndpoint'] = 'https://api.addressy.com/BankAccountValidation/Interactive/RetrieveBySortcode/v1.00/json3.ws';
  $settings['accountEndpoint'] = 'https://api.addressy.com/BankAccountValidation/Interactive/Validate/v2.00/json3.ws';
  $settings['key'] = $key;
  $js_settings['type'] = 'setting';
  $js_settings['data']['loqate'] = $settings;
  $form['#attached']['js'][] = $js_settings;
  $form['#attached']['js'][] = drupal_get_path('module', 'campaignion_loqate') . '/campaignion_loqate.min.js';
}
