<?php

function _campaignion_webform2redhen_import_submission($node, $submission) {
  $importer = new \Drupal\campaignion\CRM\Import\MappedImport();
  $submissionObj = new \Drupal\campaignion\CRM\Import\Source\WebformSubmission($node, $submission);
  if ($contact = $importer->getContact($submissionObj)) {
    $changed = $importer->import($submissionObj, $contact);
    // Allow other modules to change the contact.
    foreach (module_implements('campaignion_webform2redhen_contact_alter') as $module) {
      $function = $module . '_campaignion_webform2redhen_contact_alter';
      $changed |= $function($contact, $submissionObj, $node);
    }
    if ($changed) {
      $contact->save();
    }
  }
  return $contact;
}

function campaignion_webform2redhen_webform_submission_insert($node, $submission) {
  DrupalQueue::get('campaignion_webform2redhen')->createItem(array('nid' => $node->nid, 'sid' => $submission->sid));
}

function campaignion_webform2redhen_cron() {
  require_once drupal_get_path('module', 'webform') . '/includes/webform.submissions.inc';
  $end = time() + 10; // run for 10 seconds
  $queue = DrupalQueue::get('campaignion_webform2redhen');
  while (time() < $end && ($item = $queue->claimItem())) {
    $node = node_load($item->data['nid']);
    if ($submission = webform_get_submission($item->data['nid'], $item->data['sid'])) {
      _campaignion_webform2redhen_import_submission($node, $submission);
    } else {
      watchdog('campaignion_webform2redhen', 'Submission(!nid,!sid) has vanished before import.', array('!nid' => $item->data['nid'], '!sid' => $item->data['sid']), WATCHDOG_INFO);
    }
    $queue->deleteItem($item);
  }
}

/**
 * Implements hook_entity_insert().
 *
 * Create a drupal user for each redhen contact.
 */
function campaignion_webform2redhen_entity_insert($entity, $type) {
  if ($type != 'redhen_contact') {
    return;
  }

  $name = implode(" ", array(
    check_plain($entity->first_name),
    check_plain($entity->last_name))
  );

  // check if there's already a user with this name and attach an integer
  // to keep the username unique, if so.
  $query = new EntityFieldQuery;
  $result = $query
    ->entityCondition('entity_type', 'user')
    ->propertyCondition('name', $name)
    ->execute();
  $user_count = isset($result['user']) ? (count($result['user']) + 1) : 0;

  if($user_count > 1) {
    $name .= " ($user_count)";
  }


  $mails = field_get_items($type, $entity, 'redhen_contact_email');
  $mail = isset($mails[0]) ? check_plain($mails[0]['value']) : '';

  $new_user = entity_create('user', array(
                'name' => $name,
                'mail' => $mail,
                'status' => 1,
                'roles' => array(
                  2 => 'authenticated user',
                  5 => 'supporter',
                ),));
  entity_save('user', $new_user);

  // entity_save('user',...) sets ->uid if it succeeds.
  if(!empty($new_user->uid)) {
    $entity->uid = $new_user->uid;
    $entity->setUser();
  }
}
