<?php

/**
 * Implements hook_menu().
 */
function campaignion_manage_menu() {
  $items['campaignion/manage/content'] = array(
    'title' => 'Manage content and actions',
    'page callback' => 'campaignion_manage_content_page',
    'access arguments' => array('administer nodes'),
    'type' => MENU_SUGGESTED_ITEM,
  );
  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function campaignion_manage_admin_paths() {
  return array(
    'campaignion/manage/*' => TRUE,
  );
}

/**
 * Implements hook_theme().
 */
function campaignion_manage_theme() {
  $theme['campaignion_manage_node'] = array(
    'variables' => array(
      'node' => NULL,
      'translation_set' => FALSE,
    ),
    'file' => 'campaignion_manage.theme.inc',
  );
  return $theme;
}

function campaignion_manage_action_list($entity_type) {
  $my_actions = array();
  $actions = actions_list();
  foreach($actions as $id => &$action) {
    if ($action['type'] == $entity_type) {
      $my_actions[$id] = &$action;
    }
  }
  return $my_actions;
}

/**
 * Page callback: Manage content and actions page
 */
function campaignion_manage_content_page() {
  $baseQuery = new \Drupal\campaignion_manage\ContentQuery();
  $baseQuery->page(20);

  $listing = new \Drupal\campaignion_manage\ContentListing($baseQuery);

  $filterForm = new \Drupal\campaignion_manage\FilterForm($baseQuery, array(
    new \Drupal\campaignion_manage\ContentFilterType(),
  ));

  $bulkOpForm = new \Drupal\campaignion_manage\BulkOpForm($listing, array(
    new \Drupal\campaignion_manage\PublishBulkOp(),
  ));

  // ATTENTION: drupal_get_form() has to be called before $baseQuery->execute()
  //            as query conditions are set in the form submit handler.
  $output = array(
    'filter' => drupal_get_form('campaignion_manage_filter_form', $filterForm),
    'bulkop_listing' => drupal_get_form('campaignion_manage_bulkops_form', $bulkOpForm),
    'pager' => array(
      '#theme' => 'pager',
    ),
  );
  return $output;
}

function campaignion_manage_forms() {
  $forms['campaignion_manage_filter_form'] = array(
    'callback' => 'campaignion_manage_form',
  );
  $forms['campaignion_manage_bulkops_form'] = array(
    'callback' => 'campaignion_manage_form',
  );
  return $forms;
}

function campaignion_manage_form($form, &$form_state, $formObj) {
  $form['#formObj'] = $formObj;
  return $formObj->form($form, $form_state);
}

function campaignion_manage_form_process($form, &$form_state) {
  $form['#formObj']->process($form, $form_state);
  return $form;
}

function campaignion_manage_form_submit($form, &$form_state) {
  $form['#formObj']->submit($form, $form_state);
}

function campaignion_manage_element_info() {
  $types['campaignion_manage_content_listing'] = array(
    '#theme' => 'table',
    '#process' => array('campaignion_manage_form_process'),
  );
  return $types;
}
