<?php

/**
 * Implements hook_menu().
 */
function campaignion_manage_menu() {
  $items['campaignion/manage/content'] = array(
    'title' => 'Manage content and actions',
    'page callback' => 'campaignion_manage_content_page',
    'access arguments' => array('administer nodes'),
    'type' => MENU_SUGGESTED_ITEM,
  );
  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function campaignion_manage_admin_paths() {
  return array(
    'campaignion/manage/*',
  );
}

/**
 * Implements hook_theme().
 */
function campaignion_manage_theme() {
  $theme['campaignion_manage_node'] = array(
    'variables' => array(
      'node' => NULL,
      'translation_set' => FALSE,
    ),
    'file' => 'campaignion_manage.theme.inc',
  );
  return $theme;
}

function campaignion_manage_action_list($entity_type) {
  $my_actions = array();
  $actions = actions_list();
  foreach($actions as $id => &$action) {
    if ($action['type'] == $entity_type) {
      $my_actions[$id] = &$action;
    }
  }
  return $my_actions;
}

/**
 * Page callback: Manage content and actions page
 */
function campaignion_manage_content_page() {
  $baseQuery = new \Drupal\campaignion_manage\ContentQuery();
  $baseQuery->page(20);
  $result = $baseQuery->execute();

  $listing = new \Drupal\campaignion_manage\ContentListing();

  $filterForm = new \Drupal\campaignion_manage\FilterForm($baseQuery, array(
    new \Drupal\campaignion_manage\ContentFilterType(),
  ));

  // ATTENTION: drupal_get_form() has to be called before $baseQuery->execute()
  //            as query conditions are set in the form submit handler.
  return array(
    'filter' => drupal_get_form('campaignion_manage_filter_form', $filterForm),
    'listing' => $listing->build($baseQuery->execute()),
    'pager' => array(
      '#theme' => 'pager',
    ),
  );
}

function campaignion_manage_filter_form($form, &$form_state, $filterForm) {
  return $filterForm->form($form, $form_state);
}

function campaignion_manage_filter_form_submit($form, &$form_state) {
  $form_state['redirect'] = FALSE;
  $form_state['filterForm']->submit($form, $form_state);
}

