<?php

/**
 * Implements hook_menu().
 */
function campaignion_manage_menu() {
  $items['admin/manage'] = array(
    'title'            => t('Manage Campaignion'),
    'page callback'    => 'campaignion_manage_content_page',
    'access arguments' => array('administer nodes'),
    'type'             => MENU_NORMAL_ITEM,
  );

  $items['admin/manage/content_and_actions'] = array(
    'title'  => t('Content'),
    'type'   => MENU_DEFAULT_LOCAL_TASK,
    'weight' => -1,
  );

  $items['admin/manage/action_templates'] = array(
    'title'            => t('Action Templates'),
    'page callback'    => 'campaignion_manage_action_templates',
    'access arguments' => array('administer nodes'),
    'type'             => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function campaignion_manage_admin_paths() {
  return array(
    'campaignion/manage/*' => TRUE,
  );
}

/**
 * Implements hook_theme().
 */
function campaignion_manage_theme() {
  $theme['campaignion_manage_node'] = array(
    'variables' => array(
      'node' => NULL,
      'translation_set' => FALSE,
    ),
    'file' => 'campaignion_manage.theme.inc',
  );
  return $theme;
}

function campaignion_manage_action_list($entity_type) {
  $my_actions = array();
  $actions = actions_list();
  foreach($actions as $id => &$action) {
    if ($action['type'] == $entity_type) {
      $my_actions[$id] = &$action;
    }
  }
  return $my_actions;
}

/**
 * helper function for page callbacks
 */
function campaignion_manage_build_page(\Drupal\campaignion_manage\ContentQuery $baseQuery) {
  // add style + js for interface
  drupal_add_js(drupal_get_path('module', 'campaignion_manage') . '/js/manage_bulk.js');
  drupal_add_js(drupal_get_path('module', 'campaignion_manage') . '/js/manage_filter.js');
  drupal_add_css(drupal_get_path('module', 'campaignion_manage') . '/css/manage_bulk.css');

  $baseQuery->page(20);

  $listing = new \Drupal\campaignion_manage\ContentListing($baseQuery);
  // filter for node title created separately because it has to be enabled
  // by default and we need the machine name for the filter
  $filter_object     = new \Drupal\campaignion_manage\ContentFilterTitle();
  $filters           = array($filter_object->machineName() => $filter_object);
  $defaultActive     = array($filter_object->machineName());
  $filter_class_list = array('ContentFilterLanguage', 'ContentFilterType', 'ContentFilterStatus');
  if (module_exists('campaignion_microsite')) {
    $filter_class_list[] = 'ContentFilterMicrosite';
  }
  if (module_exists('campaignion_campaign')) {
    $filter_class_list[] = 'ContentFilterCampaign';
  }
  foreach ($filter_class_list as $filter_class) {
    $filter_class = '\Drupal\campaignion_manage\\' . $filter_class;
    if (strpos($filter_class, 'ContentFilterStatus') !== FALSE) {
      $filter_object = new $filter_class();
    }
    else {
      $filter_object = new $filter_class($baseQuery->getQuery());
    }
    $filters[$filter_object->machineName()] = $filter_object;
  }

  $filterForm = new \Drupal\campaignion_manage\FilterForm($filters, $defaultActive);
  $baseQuery->setFilter($filterForm);

  $bulkOpForm = new \Drupal\campaignion_manage\BulkOpForm($listing, array(
    new \Drupal\campaignion_manage\PublishBulkOp(),
    new \Drupal\campaignion_manage\UnpublishBulkOp(),
  ));

  // ATTENTION: drupal_get_form() has to be called before $baseQuery->execute()
  //            as query conditions are set in the form submit handler.
  $output = array(
    'filter' => drupal_get_form('campaignion_manage_filter_form', $filterForm),
    'bulkop_listing' => drupal_get_form('campaignion_manage_bulkops_form', $bulkOpForm),
    'pager' => array(
      '#theme' => 'pager',
    ),
  );
  return $output;
}

/**
 * Page callback: Manage Content & Actions page
 */
function campaignion_manage_content_page() {
  drupal_set_title(t('Manage Content & Actions'), PASS_THROUGH);

  $baseQuery = new \Drupal\campaignion_manage\ContentQuery();

  return campaignion_manage_build_page($baseQuery);
}

/**
 * Page callback: Action Templates page
 */
function campaignion_manage_action_templates() {
  drupal_set_title(t('Action Templates'), PASS_THROUGH);

  $baseQuery = new \Drupal\campaignion_manage\TemplateQuery();

  return campaignion_manage_build_page($baseQuery);
}

function campaignion_manage_forms() {
  $forms['campaignion_manage_filter_form'] = array(
    'callback' => 'campaignion_manage_form',
  );
  $forms['campaignion_manage_bulkops_form'] = array(
    'callback' => 'campaignion_manage_form',
  );
  return $forms;
}

function campaignion_manage_form($form, &$form_state, $formObj) {
  $form['#formObj'] = $formObj;
  return $formObj->form($form, $form_state);
}

function campaignion_manage_form_process($form, &$form_state) {
  $form['#formObj']->process($form, $form_state);
  return $form;
}

function campaignion_manage_form_submit($form, &$form_state) {
  $form['#formObj']->submit($form, $form_state);
}

function campaignion_manage_element_info() {
  $types['campaignion_manage_content_listing'] = array(
    '#theme' => 'table',
    '#process' => array('campaignion_manage_form_process'),
  );
  return $types;
}
