<?php
/**
 * @file
 */

/**
 * Migrate to long text field.
 */
function campaignion_overlay_update_1() {
  // migrate field config from text to long text
  db_query("UPDATE {field_config} SET type='text_long' WHERE field_name='campaignion_overlay_introduction'");
  $result = db_select('field_config', 'c')
    ->fields('c')
    ->condition('field_name', 'campaignion_overlay_introduction', '=')
    ->execute()
    ->fetchAssoc();
  $data = unserialize($result['data']);

  $data['settings'] = array();

  db_query("UPDATE {field_config} SET data=? WHERE field_name='campaignion_overlay_introduction'", array(serialize($data)));

  # change field value to text big
  db_change_field('field_data_campaignion_overlay_introduction', 'campaignion_overlay_introduction_value', 'campaignion_overlay_introduction_value', array(
    'type' => 'text',
    'size' => 'big',
  ));
  db_change_field('field_revision_campaignion_overlay_introduction', 'campaignion_overlay_introduction_value', 'campaignion_overlay_introduction_value', array(
    'type' => 'text',
    'size' => 'big',
  ));

  # field_config_instance
  $newinstances = field_read_instances(array('field_name' => 'campaignion_overlay_introduction', 'entity_type' => 'field_collection_item'));
  foreach ($newinstances as $instance) {
    $instance['settings']['text_processing'] = 1;
    $instance['widget']['type'] = 'text_textarea';
    $instance['widget']['settings'] = ['rows' => 5];
    field_update_instance($instance);
  }

  # update data values
  # wrap plain value into <em>, because those are removed from the template
  # set format
  db_query("UPDATE {field_data_campaignion_overlay_introduction} SET campaignion_overlay_introduction_format='full_html_with_editor', campaignion_overlay_introduction_value=CONCAT('<em>', campaignion_overlay_introduction_value, '</em>')");
  db_query("UPDATE {field_revision_campaignion_overlay_introduction} SET campaignion_overlay_introduction_format='full_html_with_editor', campaignion_overlay_introduction_value=CONCAT('<em>', campaignion_overlay_introduction_value, '</em>')");
}

