<?php

/**
 * @file
 * Hook implementations for the Campaignion Tracking module for GTM.
 */

/**
 * Implements hook_page_build().
 */
function campaignion_tracking_gtm_page_build(&$page) {
  $module_path = drupal_get_path('module', 'campaignion_tracking_gtm');

  // Add javascript.
  $page['content']['#attached']['js'][$module_path . '/js/campaignion_tracking_gtm.min.js'] = [
    'scope' => 'header',
    'group' => JS_LIBRARY - 100,
    'preprocess' => FALSE,
  ];
}

/**
 * Implements hook_campaignion_tracking_snippets().
 */
function campaignion_tracking_gtm_campaignion_tracking_snippets() {
  if ($tag_id = variable_get('campaignion_tracking_gtm_id')) {
    $exports['gtm'] = <<<SCRIPT
      (function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
      new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
      j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
      'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
      })(window,document,'script','dataLayer','$tag_id');
      SCRIPT;
    return $exports;
  }
}
