<?php

/**
 * Implements hook_cron().
 */
function campaignion_engagement_cron() {
  $last_activity_id = variable_get('campaignion_engagement_last_cron_activity_id');

  // Engagements for webform submissions.
  $sql = <<<SQL
SELECT activity_id, contact_id, nid, type
  FROM {campaignion_activity}
  INNER JOIN {campaignion_activity_webform} USING(activity_id)
  INNER JOIN {node} USING(nid)
WHERE activity_id>:last AND type='webform_submission'
LIMIT 100
SQL;
  $result = db_query($sql, array(':last' => $last_activity_id['webform_submission']));

  foreach ($result as $row) {
    redhen_engagement_create('webform_submission_' . $row->type, $row->contact_id, 'Webform submission', 'node', $row->nid);
    $last_activity_id['webform_submission'] = $row->activity_id;
    variable_set('campaignion_engagement_last_cron_activity_id', $last_activity_id);
  }

  // Engagement for comments.
  $sql = <<<SQL
SELECT activity_id, contact_id, nid, type
  FROM {campaignion_activity}
  INNER JOIN {campaignion_activity_comment} USING(activity_id)
  INNER JOIN {node} USING(nid)
WHERE activity_id>:last AND type='comment'
LIMIT 100
SQL;
  $result = db_query($sql, array(':last' => $last_activity_id['comment']));

  foreach ($result as $row) {
    redhen_engagement_create('comment_' . $row->type, $row->contact_id, 'Comment', 'comment', $row->cid);
    $last_activity_id['comment'] = $row->activity_id;
    variable_set('campaignion_engagement_last_cron_activity_id', $last_activity_id);
  }
}
