<?php

// Filter for css files.
function _campaignion_vue_filter_css($filename) {
  return (strpos($filename, '.css') === strlen($filename) - 4);
}

// Add scripts, settings and styles needed by vue apps.
function _campaignion_vue_add_assets() {
  $module_path = drupal_get_path('module', 'campaignion_vue') . '/';

  // Add javascript.
  drupal_add_js($module_path . '/js/campaignion_vue.min.js', [
    'scope' => 'footer',
    'group' => JS_LIBRARY,
    'preprocess' => FALSE,
  ]);

  // Add element-ui locale.
  $lang = $GLOBALS['language']->language;
  if (substr($lang, 0, 2) != 'en') {
    $strings = file_get_contents($module_path . 'locale/' . $lang . '.json');
  }
  if (!empty($strings)) {
    drupal_add_js(
      array(
        'campaignion_vue' => array(
          'element_ui_strings' => json_decode($strings, TRUE),
        )
      ),
      'setting'
    );
  }

  // Add element-ui stylesheets.
  $stylesheets = array_filter(scandir($module_path . 'css'), '_campaignion_vue_filter_css');
  foreach ($stylesheets as $stylesheet) {
    drupal_add_css($module_path . 'css/' . $stylesheet);
  }
}

/**
 * Implements hook_preprocess_html().
 */
function campaignion_vue_preprocess_html(&$vars) {
  $js = drupal_add_js();
  $found = FALSE;
  foreach ($js as $path => $options) {
    if (substr($path, -11) == '.vue.min.js') {
      $found = TRUE;
      break;
    }
  }
  if ($found) {
    _campaignion_vue_add_assets();
  }
}
