<?php
/**
 * @file
 * Code for the campaignion_views_interface feature.
 */

include_once 'campaignion_views_interface.features.inc';

/**
 * we define the path where we want to group the various views displays into tabs
 */
function campaignion_views_interface_menu() {
}

/**
 * Implements hook_menu_alter().
 */
function campaignion_views_interface_menu_alter(&$items) {
  $items['admin/manage/navigation_and_structure/menu'] = array(
    'type' => MENU_DEFAULT_LOCAL_TASK,
    'tab_parent' => 'admin/manage/navigation_and_structure',
    'tab_root' => 'admin/manage/navigation_and_structure',
  ) + $items['admin/structure/menu'];
  $items['admin/manage/navigation_and_structure/menu/add'] = array(
    'tab_parent' => 'admin/manage/navigation_and_structure/menu',
    'tab_root' => 'admin/manage/navigation_and_structure',
  ) + $items['admin/structure/menu/add'];
  $items['admin/manage/navigation_and_structure/taxonomy'] = array(
    'type' => MENU_LOCAL_TASK,
    'tab_parent' => 'admin/manage/navigation_and_structure',
    'tab_root' => 'admin/manage/navigation_and_structure',
  ) + $items['admin/structure/taxonomy'];
  $items['admin/manage/navigation_and_structure/taxonomy/add'] = array(
    'tab_parent' => 'admin/manage/navigation_and_structure/taxonomy',
    'tab_root' => 'admin/manage/navigation_and_structure',
  ) + $items['admin/structure/taxonomy/add'];

  $items['admin/manage/navigation_and_structure'] = array(
    'title' => 'Navigation and structure',
    'tab_root' => NULL,
    'tab_parent' => NULL,
    'type' => MENU_CALLBACK,
  );
  $items['admin/manage/navigation_and_structure'] += $items['admin/manage/navigation_and_structure/menu'];
}

/**
 * Implements hook_form_ID_alter().
 *
 * fix the exposed filter for actions
 */
function campaignion_views_interface_form_views_exposed_form_alter(&$form, &$form_state, $form_id) {

  if ($form['#id'] == 'views-exposed-form-supporters-page') {

    $options = array(
      'All' => '-Any-',
    );

    include_once drupal_get_path('module', 'mo_utilities') . '/mo_node.inc';
    $options += \MO\Nodes\get_titles_from_types(array('petition', 'donation', 'email_protest'));

    $form['message_ae_action_node_nid']['#options']       = $options;
    $form['message_ae_action_node_nid']['#default_value'] = array();
    $form['message_ae_action_node_nid']['#multiple']      = FALSE;
    $form['message_ae_action_node_nid']['#size']          = 1;
  }

  if ($form['#id'] === 'views-exposed-form-manage-content-actions-page-1') {
    $options = $form['type_1']['#options'];
    unset($options['webform_template_type']);
    $form['type_1']['#options'] = $options;
  }
}

