<?php
/**
 * @file
 * Campaignion newsletter CleverReach integration module.
 */

module_load_include('php', 'campaignion_newsletters_cleverreach', 'cleverreach.api');

/**
 * Implements hook_campaignion_newsletters_provider_info().
 */
function campaignion_newsletters_cleverreach_campaignion_newsletters_provider_info() {
  return \Drupal\campaignion_newsletters_cleverreach\CleverReach::getInstance();
}

/**
 * Implements hook_campaignion_newsletters_subscribed().
 */
function campaignion_newsletters_cleverreach_campaignion_newsletters_subscribed($newsletter, $email) {
  $api = \Drupal\campaignion_newsletters_cleverreach\CleverReach::getInstance();
  if ($api->hasList($newsletter)) {
    $api->subscribe($newsletter, $email);
  }
}

/**
 * Implements hook_campaignion_newsletters_unsubscribed().
 */
function campaignion_newsletters_cleverreach_campaignion_newsletters_unsubscribed($newsletter, $email) {
  $api = \Drupal\campaignion_newsletters_cleverreach\CleverReach::getInstance();
  if ($api->hasList($newsletter)) {
    $api->unsubscribe($newsletter, $email);
  }
}


/**
 * Get the API key for a machine_name.
 */
function campaignion_newsletters_cleverreach_get_key($machine_name) {
  $keys = variable_get('cleverreach_api_keys', array());
  if (isset($keys[$machine_name])) {
    return $keys[$machine_name];
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 * Implements hook_form_campaignion_newsletters_admin_settings_alter().
 */
function campaignion_newsletters_cleverreach_form_campaignion_newsletters_admin_settings_alter(&$form, &$form_state) {
  $form['cleverreach'] = array(
    '#type' => 'fieldset',
    '#title' => t('CleverReach'),
    '#weight' => 1,
    '#collapsible' => TRUE,
    '#collapsed' => FALSE,
    '#tree' => TRUE,
  );
  $form['cleverreach']['api_keys'] = array(
    '#type' => 'fieldset',
    '#title' => t('API-Keys'),
    '#prefix' => '<div id="cleverreach-api-keys-wrapper">',
    '#suffix' => '</div>',
  );
  $fs = &$form['cleverreach']['api_keys'];
  $keys = variable_get('cleverreach_api_keys', array());
  if (empty($form_state['cleverreach_new_keys'])) {
    $form_state['cleverreach_new_keys'] = count($keys) ? 0 : 1;
  }
  foreach ($keys as $name => $key) {
    $fs[$name]['name'] = array(
      '#type' => 'machine_name',
      '#machine_name' => array(
        'exists' => 'campaignion_newsletters_cleverreach_get_key',
      ),
      '#title' => t('Machine name'),
      '#default_value' => $name,
      '#disabled' => TRUE,
    );
    $fs[$name]['key'] = array(
      '#type' => 'textfield',
      '#default_value' => $key,
      '#title' => t('API-Key'),
    );
  }
  if (!empty($form_state['cleverreach_new_keys'])) {
    for ($i = 1; $i <= $form_state['cleverreach_new_keys']; $i++) {
      $name = 'new_' . $i;
      $fs[$name]['name'] = array(
        '#type' => 'machine_name',
        '#machine_name' => array(
          'exists' => 'campaignion_newsletters_cleverreach_get_key',
        ),
        '#title' => t('Machine name'),
        '#default_value' => '',
        '#required' => FALSE,
      );
      $fs[$name]['key'] = array(
        '#type' => 'textfield',
        '#default_value' => '',
        '#title' => t('API-Key'),
      );
    }
  }
  $fs['add_more'] = array(
    '#type' => 'submit',
    '#value' => t('Add another key'),
    '#limit_validation_errors' => array(),
    '#ajax' => array(
       'callback' => 'campaignion_newsletters_cleverreach_admin_ajax',
       'wrapper' => 'cleverreach-api-keys-wrapper',
    ),
    '#submit' => array('campaignion_newsletters_cleverreach_admin_add_more_submit'),
  );
  $form['cleverreach']['wsdl_url'] = array(
    '#type' => 'textfield',
    '#default_value' => variable_get('cleverreach_wsdl_url', 'http://api.cleverreach.com/soap/interface_v5.1.php?wsdl'),
    '#title' => t('WSDL-URL'),
  );

  array_unshift(
    $form['#submit'],
    'campaignion_newsletters_cleverreach_admin_submit'
  );
  array_unshift(
    $form['#validate'],
    'campaignion_newsletters_cleverreach_admin_validate'
  );
}

/**
 * Ajax callback for the add-more keys button.
 */
function campaignion_newsletters_cleverreach_admin_ajax($form, &$form_state) {
  return $form['cleverreach']['api_keys'];
}

/**
 * Submit callback for the add-more keys button.
 */
function campaignion_newsletters_cleverreach_admin_add_more_submit($form, &$form_state) {
  $form_state['cleverreach_new_keys']++;
  $form_state['rebuild'] = TRUE;
}

/**
 * Validate callback for the admin form.
 */
function campaignion_newsletters_cleverreach_admin_validate($form, &$form_state) {
  $keys = &$form_state['values']['cleverreach']['api_keys'];
  foreach ($keys as $key => $data) {
    if (empty($data['name']) && empty($data['key'])) {
      continue;
    }
    if (empty($data['name'])) {
      form_set_error('cleverreach][api_keys][' . $key . '][name', t('The API key has to have a unique name.'));
    }
  }
}

/**
 * Submit callback for the admin form.
 */
function campaignion_newsletters_cleverreach_admin_submit($form, &$form_state) {
  $keys = array();
  foreach ($form_state['values']['cleverreach']['api_keys'] as $data) {
    if (!empty($data['key'])) {
      $keys[$data['name']] = $data['key'];
    }
  }
  variable_set('cleverreach_api_keys', $keys);
  variable_set('cleverreach_wsdl_url', $form_state['values']['cleverreach']['wsdl_url']);
  // Hide our values from the general submit handler.
  unset($form_state['values']['cleverreach']);
}
