<?php

/**
 * @file
 * Main module file that implements hooks and callbacks.
 */

use Drupal\campaignion_auth\AuthAppClient;

/**
 * Implements hook_little_helpers_services().
 */
function campaignion_auth_little_helpers_services() {
  $info['campaignion_auth.AuthAppClient'] = [
    'class' => AuthAppClient::class,
    'arguments' => [
      '!campaignion_auth_app_url',
      '!campaignion_auth_api_key',
      '!campaignion_organization',
    ],
  ];
  return $info;
}

/**
 * Implements hook_d7csp_csp_hosts().
 */
function campaignion_auth_d7csp_hosts() {
  $hosts = [];
  if ($url = variable_get_value('campaignion_auth_app_url')) {
    $parts = parse_url($url);
    $hosts['connect-src'][] = "{$parts['scheme']}://{$parts['host']}";
  }
  return $hosts;
}
