root: true
plugins:
  - babel
  - html
  - mocha
extends:
  - standard
  - plugin:vue/base
env:
  browser: true
  mocha: true
globals:
  assert: false
  Drupal: false
  globalThis: false
rules:
  allow-parens: 0
  generator-star-spacing: 0
  no-multi-spaces:
    - error
    - {ignoreEOLComments: true}
  no-debugger: 0
overrides:
  -
    files: test/**/specs/**/*.js
    rules:
      no-unused-expressions: off
